### Zmienne globalne
@baseUrl = http://192.168.88.250:80/users
@uid = user_12345
@testCode = 999888

### 1. Generowanie kodu dla użytkownika
POST {{baseUrl}}/code
Content-Type: application/json

{
    "id_uid": "{{uid}}"
}

---

### 2. Weryfikacja wieku (Główny proces)
POST {{baseUrl}}/verify-age
Content-Type: application/json

{
    "requested_age": 18,
    "code": "{{testCode}}",
    "meta": {
        "service_name": "Sklep Monopolowy",
        "location": "Warszawa, ul. Wiejska"
    }
}

---

### 3. Czyszczenie / Unieważnienie kodu
POST {{baseUrl}}/clear-code
Content-Type: application/json

{
    "id_uid": "{{uid}}"
}